Emit:
test.m:2:14: error: expected ';' after @class
@ class foo  int x;
             ^

instead of silently accepting the malformed input.


git-svn-id: http://llvm.org/svn/llvm-project/cfe/cfe/trunk@39100 91177308-0d34-0410-b5e6-96231b3b80d8