On bogus code like this:
  int *P2;
  P2(1, 2, 3);

  register short X;
  X();

emit:

ds.c:10:3: error: called object is not a function or function pointer
  P2(1, 2, 3);
  ^~~~~~~~~~~
ds.c:13:3: error: called object is not a function or function pointer
  X();
  ^~~

instead of aborting.


git-svn-id: http://llvm.org/svn/llvm-project/cfe/cfe/trunk@39599 91177308-0d34-0410-b5e6-96231b3b80d8