record accurate sourceloc info for storage class specs, so we can report things like:
t.c:4:10: error: invalid storage class specifier in function declarator
int foo2(auto int Aaslfkasdflkj, register B);
         ^

instead of:

t.c:4:19: error: invalid storage class specifier in function declarator
int foo2(auto int Aaslfkasdflkj, register B);
                  ^


git-svn-id: http://llvm.org/svn/llvm-project/cfe/cfe/trunk@39224 91177308-0d34-0410-b5e6-96231b3b80d8